### ISSUE TITLE
Question: How does AWS help customers achieve compliance in the cloud?

### ISSUE THREAD

**Issue by SUN-Xiaoying** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers#10]
How does AWS help customers achieve compliance in the cloud?

A. It's not possible to meet regulatory compliance requirements in the Cloud.
B. AWS applies the most common Cloud security standards, and is responsible for complying with customers’ applicable laws and regulations.
C. AWS has many common assurance certifications such as ISO 9001 and HIPAA.
D. Many AWS services are assessed regularly to comply with local laws and regulations.

Correct Answer is given C:
Why not D?
D. Many AWS services are assessed regularly to comply with local laws and regulations.

AWS provides a wide range of compliance resources and services to help customers achieve compliance in the cloud. AWS services are designed with security and compliance in mind, and AWS offers various compliance programs and certifications, including SOC 2, HIPAA, PCI DSS, and ISO 27001, among others, which demonstrate their commitment to security and compliance. AWS customers can leverage these resources and certifications to help them meet regulatory compliance requirements in the cloud.

Option B is not entirely accurate. While AWS does provide a secure and compliant infrastructure, customers are also responsible for ensuring that their own applications and workloads comply with applicable laws and regulations. AWS follows the shared responsibility model, where both AWS and the customer have responsibilities for security and compliance.

Option C is correct in stating that AWS holds many common assurance certifications, which can be beneficial for customers looking to achieve compliance, but the certifications themselves do not automatically ensure compliance for customer workloads. Customers must still configure and use AWS services in a compliant manner to meet their specific regulatory requirements.

**Comment by danieldanielecki** [comment]
Thank you for the elaborative answer, @SUN-Xiaoying.
It's indeed a tricky question and I wrote it down not correctly:)

I fixed it in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers/commit/aa01cca7d42112e9f9466839764da1a6117b0476 thanks to you contribution!
