### ISSUE TITLE
Question 568: BD

### ISSUE THREAD

**Issue by SUN-Xiaoying** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers#11]
A company wants to migrate its applications to a VPC on AWS These applications will need to access on-premises resources. What combination of actions will enable the company to accomplish this goals? (Select TWO)

 Use the AWS Service Catalog to identify a list of on-premises resources that can be migrated
 Build a VPN connection between an on-premises device and a virtual private gateway in the new VPC
 Use Amazon Athena to query data from the on-premises database servers
 Connect the company's on-premises data center to AWS using AWS Direct Connect
 Leverage Amazon CloudFront to restrict access to static web content provided through the company's on-premises web servers
 
 https://www.examtopics.com/discussions/amazon/view/78647-exam-aws-certified-cloud-practitioner-topic-1-question-65/
 
 Correct answer should be BD?

**Comment by danieldanielecki** [comment]
@SUN-Xiaoying, thanks :) you're correct!
Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers/commit/1f51274e7c01c4486c80d85d22f3f13ce8043843
