### ISSUE TITLE
Question 513: C

### ISSUE THREAD

**Issue by SUN-Xiaoying** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers#13]
A company needs 24/7 phone email and chat access with a response time of less than 1 hour if a production system has a service interruption Which AWS Support plan meets these requirements at the LOWEST cost?

C. Business!

**Comment by danieldanielecki** [comment]
@SUN-Xiaoying, correct 👍 

Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers/commit/45118a8787bb69407a9cf9bcffcc073731645d31, thank you!
